version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing node JS
    finally:
      - echo Install phase finished
  pre_build:
    commands:
      - echo Installing some packages and source NPM dependencies...
      - wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
      - echo "creating environment variable"
      - npm install
    finally:
      - echo Pre-build phase finished  on `date` 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` 
      - npm run build
  
artifacts:
  files:
    - '**/*'
