version: '3'

services:
  web:
    container_name: glam-client
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    env_file:
      - .env