version: '3'

services:
  web:
    container_name: glam-client
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    ports:
      - 80:80
    restart: always
    env_file:
      - .env

# testing terraform codepipeline on 4th April 9:23 PM