version: '3'

services:
  web:
    container_name: glam-client
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
    ports:
      - 80:80
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env