version: '3'

services:
  web:
    container_name: glam-client
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:80
    restart: always
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000