version: '3'

services:
  web:
    container_name: glam-client
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
    ports:
      - 80:80
    restart: always
    env_file:
      - .env

# testing terraform codepipeline on 3rd April 12:55 AM